sensorapi:
  avg: 1
  span: 504

train_test_split:
  cutoff_hours: 120.0

model: "HoltWinters"

hyper_params:
  h: 24
  season_length: 24

conformal_prediction:
  n_windows: 2
  levels: [90]

freq: "H"

evaluation:
  metrics: ["mae"]

utilsforecast_module_path: "utilsforecast.losses"

statsforecast_module_path: "statsforecast.model"
